package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/pocketbase/dbx"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/core"
)

func seedNotificationMessageUpgrade(t *testing.T, app core.App) string {
	t.Helper()
	if err := ensureSchema(app); err != nil {
		t.Fatal(err)
	}
	user, _ := createRouteTestUser(t, app, "authenticated")
	// 只在隔离测试中恢复迁移前的实际存储边界；正常运行时始终由数据库拒绝旧写入。
	for name := range notificationMessageGuardStatements() {
		if _, err := app.DB().NewQuery("DROP TRIGGER " + name).Execute(); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := app.DB().NewQuery("DELETE FROM " + schemaDataMigrationsTable + " WHERE name = {:name}").Bind(dbx.Params{"name": notificationMessageMigration}).Execute(); err != nil {
		t.Fatal(err)
	}
	result := largeNotificationJobResult(10)
	job, _, err := createNotificationJob(app, user.Id, localScheduleDecision{localScheduleOccurrence: result.Schedule}, notificationStatusFailed, 2)
	if err != nil {
		t.Fatal(err)
	}
	job.Set("result", result)
	if err := app.Save(job); err != nil {
		t.Fatal(err)
	}
	return user.Id
}

func TestNotificationMessageMigrationRollsBackWithMarker(t *testing.T) {
	app := newSchemaTestApp(t)
	userID := seedNotificationMessageUpgrade(t, app)
	if _, err := app.DB().NewQuery("CREATE TRIGGER fail_message_upgrade BEFORE INSERT ON notification_job_messages BEGIN SELECT RAISE(ABORT, 'injected migration failure'); END").Execute(); err != nil {
		t.Fatal(err)
	}
	if err := ensureSchema(app); err == nil {
		t.Fatal("migration ignored storage failure")
	}
	applied, err := schemaDataMigrationApplied(app, notificationMessageMigration)
	if err != nil || applied {
		t.Fatalf("failed migration published its marker: %v", err)
	}
	hasOldMessage, err := notificationMessageHistoryExists(app)
	if err != nil || !hasOldMessage {
		t.Fatalf("failed migration lost original message: %v", err)
	}
	if _, err := app.DB().NewQuery("DROP TRIGGER fail_message_upgrade").Execute(); err != nil {
		t.Fatal(err)
	}
	if err := ensureSchema(app); err != nil {
		t.Fatal(err)
	}
	before, err := loadNotificationHistoryJobs(app, userID, "all", 20, 0)
	if err != nil || len(before) != 1 {
		t.Fatalf("retry failed: %v", err)
	}
	operations, err := measureSubscriptionDBOperations(app, func() error { return runSchemaDataMigrations(app) })
	if err != nil {
		t.Fatal(err)
	}
	// 既有账本 CREATE IF NOT EXISTS 不等于回填；只对本次负责的消息事实检查重复扫描和写入。
	for _, statement := range operations.WriteSQL {
		if strings.Contains(strings.ToLower(statement), "notification_job") {
			t.Fatalf("repeated migration rewrote message storage: %s", statement)
		}
	}
	for _, statement := range operations.ReadSQL {
		if strings.Contains(strings.ToLower(statement), "from notification_jobs") {
			t.Fatalf("repeated migration scanned history: %s", statement)
		}
	}
	after, err := loadNotificationHistoryJobs(app, userID, "all", 20, 0)
	if err != nil || !reflect.DeepEqual(before, after) {
		t.Fatalf("repeated migration changed history: %v", err)
	}
}

func TestNotificationMessageMigrationRequiresRecoveryPoint(t *testing.T) {
	app := newSchemaTestApp(t)
	seedNotificationMessageUpgrade(t, app)
	hook := app.OnBackupCreate().BindFunc(func(*core.BackupEvent) error { return errors.New("snapshot unavailable") })
	if err := prepareExclusiveSchemaDataMigrations(app); err == nil {
		t.Fatal("migration proceeded without a recovery point")
	}
	app.OnBackupCreate().Unbind(hook)
	if err := prepareExclusiveSchemaDataMigrations(app); err != nil {
		t.Fatal(err)
	}
	if exists, err := inspectSchemaMigrationRecoveryPoint(app, notificationMessageRecoveryPoint); err != nil || !exists {
		t.Fatalf("missing recovery point: %v", err)
	}
}

func TestNotificationMessageHistoricalUpgradeMatrix(t *testing.T) {
	directory := os.Getenv("RENEWLET_NOTIFICATION_UPGRADE_FIXTURES")
	if directory == "" {
		t.Skip("requires checksummed databases generated by the five immutable historical tags")
	}
	versions := map[string]string{
		"v0.2.95": "02fec668d65ad6b03ba0321301abf05e17ba28dd",
		"v0.2.96": "d2755510203c8eaf7f8454aca22a36885c62a6cc",
		"v0.3.21": "dee5d8c8cf055583d9c45eb82a0b41e0cd13e016",
		"v0.3.24": "7390d2596db2ec018e0fa0593836d3f1f6e78b74",
		"v0.3.25": "385e139b098de0b72b7e6fe879bf1462c53fd645",
	}
	for version, revision := range versions {
		t.Run(version, func(t *testing.T) {
			base := filepath.Join(directory, version)
			var origin struct {
				Revision     string `json:"revision"`
				DatabaseHash string `json:"databaseHash"`
				ExpectedHash string `json:"expectedHash"`
			}
			data, err := os.ReadFile(filepath.Join(base, "origin.json"))
			if err != nil {
				t.Fatal(err)
			}
			if err := json.Unmarshal(data, &origin); err != nil {
				t.Fatal(err)
			}
			if origin.Revision != revision {
				t.Fatal("historical source revision mismatch")
			}
			database := readNotificationUpgradeFixture(t, filepath.Join(base, "data.db"), origin.DatabaseHash)
			expectedBytes := readNotificationUpgradeFixture(t, filepath.Join(base, "expected.json"), origin.ExpectedHash)
			var expected struct {
				UserID string          `json:"userId"`
				Result json.RawMessage `json:"result"`
			}
			if err := json.Unmarshal(expectedBytes, &expected); err != nil {
				t.Fatal(err)
			}
			dataDir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dataDir, "data.db"), database, 0600); err != nil {
				t.Fatal(err)
			}
			var first []notificationHistoryJob
			for restart := 0; restart < 2; restart++ {
				app := pocketbase.NewWithConfig(pocketbase.Config{DefaultDataDir: dataDir})
				registerAuthHooks(app)
				if err := app.Bootstrap(); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() { _ = app.ResetBootstrapState() })
				if err := prepareExclusiveSchemaDataMigrations(app); err != nil {
					t.Fatal(err)
				}
				if err := app.RunAppMigrations(); err != nil {
					t.Fatal(err)
				}
				if err := ensureSchema(app); err != nil {
					t.Fatal(err)
				}
				history, err := loadNotificationHistoryJobs(app, expected.UserID, "all", 20, 0)
				if err != nil || len(history) != 1 {
					t.Fatalf("historical message missing: %v", err)
				}
				var actual, want map[string]interface{}
				if err := json.Unmarshal(history[0].Result, &actual); err != nil {
					t.Fatal(err)
				}
				if err := json.Unmarshal(expected.Result, &want); err != nil {
					t.Fatal(err)
				}
				if version == "v0.2.95" {
					// v0.2.95 的历史金额仍为 number；一次性升级沿用既有六位小数金额规则，正文保持原字符串。
					message := want["message"].(map[string]interface{})
					items := message["items"].([]interface{})
					items[0].(map[string]interface{})["price"] = "12.5"
				}
				if !reflect.DeepEqual(actual, want) {
					t.Fatalf("historical result changed: got=%s want=%s", history[0].Result, expected.Result)
				}
				if restart == 0 {
					first = history
				} else if !reflect.DeepEqual(first, history) {
					t.Fatal("restart changed historical result")
				}
				if err := app.ResetBootstrapState(); err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}

func TestNotificationMessageHistoricalPayloadContract(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "packages", "shared", "src", "contract-fixtures", "notification-message-upgrade-fixtures.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fixtures struct {
		Fixtures []struct {
			Version string          `json:"version"`
			Result  json.RawMessage `json:"result"`
		} `json:"fixtures"`
	}
	if err := json.Unmarshal(data, &fixtures); err != nil {
		t.Fatal(err)
	}
	for _, fixture := range fixtures.Fixtures {
		t.Run(fixture.Version, func(t *testing.T) {
			app := newSchemaTestApp(t)
			userID := seedNotificationMessageUpgrade(t, app)
			if _, err := app.DB().NewQuery("UPDATE notification_jobs SET result = {:result} WHERE user = {:user}").Bind(dbx.Params{"result": string(fixture.Result), "user": userID}).Execute(); err != nil {
				t.Fatal(err)
			}
			if err := ensureSchema(app); err != nil {
				t.Fatal(err)
			}
			history, err := loadNotificationHistoryJobs(app, userID, "all", 20, 0)
			if err != nil || len(history) != 1 {
				t.Fatalf("historical snapshot missing: %v", err)
			}
			var actual, expected map[string]interface{}
			if err := json.Unmarshal(history[0].Result, &actual); err != nil {
				t.Fatal(err)
			}
			if err := json.Unmarshal(fixture.Result, &expected); err != nil {
				t.Fatal(err)
			}
			if fixture.Version == "v0.2.95" {
				expected["message"].(map[string]interface{})["items"].([]interface{})[0].(map[string]interface{})["price"] = "12.5"
			}
			if !reflect.DeepEqual(actual, expected) {
				t.Fatal("historical public result changed")
			}
		})
	}
}

func readNotificationUpgradeFixture(t *testing.T, path, expectedHash string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	hash := sha256.Sum256(data)
	if expectedHash == "" || hex.EncodeToString(hash[:]) != expectedHash {
		t.Fatalf("historical fixture checksum mismatch: %s", path)
	}
	return data
}
